language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
script: nosetests
sudo: false
deploy:
  provider: pypi
  user: passy
  on:
    tags: true
    repo: passy/flask-oidc
  distributions: sdist bdist_wheel
  password:
    secure: FZGzXhgf2o+nq29GDaLaEMdK/FfhLNMUMM/Y9yH1DwSsF709dochZFmuzioKhbukusOCgQGJj5+BrW82e4KlYX7nBBvLsycKR3/FO9TLm5BBue3ZfTmHgEFW0rP7VUQ21ziy8+6eipHxRQo8KCJwj8TFWK/1ELiXNi01EuVGg1Q=
